---
all:
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ lookup('env', 'HOME') }}/.local/share/pipx/venvs/ansible-core/bin/python"

  hosts:
    localhost:

  children:
    vm:
      hosts:
        vm-jarvis:
