# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/proxmox-vm

- name: Import download_image task
  ansible.builtin.import_tasks: download_image.yml
  tags:
    - download_image

- name: Import create_vm task
  ansible.builtin.import_tasks: create_vm.yml
  tags:
    - create_vm

- name: Import start_vm task
  ansible.builtin.import_tasks: start_vm.yml
  tags:
    - start_vm

- name: Import stop_vm task
  ansible.builtin.import_tasks: stop_vm.yml
  tags:
    - stop_vm

- name: Import remove_vm task
  ansible.builtin.import_tasks: remove_vm.yml
  tags:
    - remove_vm
