# SPDX-License-Identifier: MIT-0
---
# vars file for roles/proxmox-vm

debian_target_release: trixie

debian_releases:
  trixie:
    base_url: 'https://cloud.debian.org/images/cloud/trixie/latest'
    target_file: 'debian-13-genericcloud-amd64.qcow2'
    checksum_algorithm: sha512
    checksum_url: "{{ debian_releases.trixie.base_url ~ '/SHA512SUMS' }}"
    regex: "^([a-fA-F0-9]{128})\\s+{{ debian_releases.trixie.target_file }}$"
    ostype: l26
    pve_storage: local
    pve_content_type: import

current_image: "{{ debian_releases[debian_target_release] }}"

pve_template_src_path: "{{ current_image.pve_storage }}:{{ current_image.pve_content_type }}/{{ current_image.target_file }}"
