---
- name: Test local Proxmox VM role
  hosts: localhost
  gather_facts: false

  vars:
    proxmox_api: &proxmox_api
      api_host: "{{ proxmox_api_host }}"
      api_user: "{{ proxmox_api_user }}"
      api_token_id: "{{ proxmox_api_token_id }}"
      api_token_secret: "{{ proxmox_api_token_secret }}"
      validate_certs: "{{ proxmox_validate_certs }}"

  module_defaults:
    group/community.proxmox.proxmox: *proxmox_api

  tasks:
    - name: Include Proxmox VM cloud image provisioning tasks
      ansible.builtin.include_role:
        name: proxmox-vm
        tasks_from: download_image
